# https://yamllint.readthedocs.io/en/stable/rules.html
extends: default
rules:
  # 120 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 100
    level: warning
  document-start:
    present: false
  indentation: disable
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  key-duplicates: {}
