version: "3.9"

# Use this docker-compose file to setup the test environment before running the
# tests.

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      ENVIRONMENT: test
    depends_on:
      - couchbase
      - minio
      - nsqlookupd-1
      - nsqlookupd-2
      - nsqd-1
      - nsqd-2
      - nsqd-3

  couchbase:
    image: couchbase/server:6.6.0
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - "./storage/couchbase:/opt/couchbase/var"
 
  minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data

  nsqlookupd-1:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqlookupd
      -broadcast-address localhost:4160
      -log-level error
    ports:
      - 4160:4160
      - 4161:4161

  nsqlookupd-2:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqlookupd
      -broadcast-address localhost:4162
      -log-level error
    ports:
      - 4162:4160
      - 4163:4161

  nsqd-1:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqd
      -broadcast-address localhost:4150
      -lookupd-tcp-address nsqlookupd-1:4160
      -lookupd-tcp-address nsqlookupd-2:4160
      -log-level error
    ports:
      - 4150:4150
      - 4151:4151
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2

  nsqd-2:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqd
      -broadcast-address localhost:4152
      -lookupd-tcp-address nsqlookupd-1:4160
      -lookupd-tcp-address nsqlookupd-2:4160
      -log-level error
    ports:
      - 4152:4150
      - 4153:4151
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2

  nsqd-3:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqd
      -broadcast-address localhost:4154
      -lookupd-tcp-address nsqlookupd-1:4160
      -lookupd-tcp-address nsqlookupd-2:4160
      -log-level error
    ports:
      - 4154:4150
      - 4155:4151
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2


volumes:
  minio_data:
  couchbase_demo:
