version: "3.9"

# Use this docker-compose file to setup the test environment before running the
# tests.

services:
  couchbase:
    image: couchbase/server:6.6.2
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - "./storage/couchbase:/opt/couchbase/var"

  nsqlookupd:
    image: nsqio/nsq:v1.2.1
    command: >
      /nsqlookupd --log-level=error
    hostname: nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161

  nsqd:
    image: nsqio/nsq:v1.2.1
    command: >
      /nsqd --lookupd-tcp-address=nsqlookupd:4160 --max-msg-size=1413820683
      --log-level=error
    hostname: nsqd
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151

  nsqadmin:
    image: nsqio/nsq:v1.2.1
    command: >
      /nsqadmin --lookupd-http-address=nsqlookupd:4161 --log-level=error
    hostname: nsqadmin
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

volumes:
  minio_data:
  couchbase_data:
