# Config used for devcontainer development.

# General app config.
address = ":8080" # The IP:Port. Defaults to 8080.
log_level = "debug" # Log level. Defaults to info.
jwt_signkey = "secret" # JWT sign key secret.
jwt_expiration = 72 # JWT expiration in hours. Defaults to 72 hours (3 days)
max_file_size = 64 # Maximum file size to allow for samples in MB.
max_avatar_file_size = 1 # Maximum avatar size to allow for user profile picture in MB.

[ui]
address = "http://localhost:8000" # DSN for the frontend.

[db]
server = "couchbase://couchbase" # DSN for connecting to the database
username = "Administrator" # Username used to access the db.
password = "password" # Password used to access the db.
bucket_name = "sfw" # Name of the couchbase bucket.

[nsq]
address = "nsqd:4150"

[storage]
endpoint = "minio:9000"
seckey = "minio123"
accesskey = "minio"
spacename = "samples"
avatarspace = "images"
ssl = false

[smtp]
server = "smtp.example.com"
port = 465
user =  "user@example.com"
password = "password"
identity =  "identity"
sender =  "sender@example.com"