# Config used for local development.
# All dependent services (NSQ, Couchbase, ..) are assumed running in the
# same context.
# App own config.
address = ":8080" # The IP:Port. Defaults to 8080.
log_level = "debug" # Log level. Defaults to info.
signkey = "secret" # JWT sign key secret.
max_file_size = 64 # Maximum file size to allow for samples in MB.
max_avatar_file_size = 1 # Maximum avatar size to allow for user profile
# picture in MB.

[ui]
address = "http://localhost:8000"

[db]
server = "couchbase://localhost" # DSN for connecting to the database
username = "Administrator" # Username used to access the db.
password = "password" # Password used to access the db.

[nsq]
address = "localhost:4150"

[storage]
endpoint = "localhost:9000"
seckey = "minio123"
accesskey = "minio"
spacename = "samples"
avatarspace = "images"
ssl = false

[smtp]
server = "smtp.example.com"
port = 465
user = "user@example.com"
password = "password"
identity = "identity"
sender = "sender@example.com"
