### docker-compose dev config.

[ui]
address = "http://localhost:8000"

[app]
address = ":8080"
domain = "localhost"
tmp_samples = "/tmp/samples"
max_file_size = 64000000 # 64MB
max_avatar_file_size = 100000 # 100KB
admin_user = "admin"
admin_pwd = "password"
admin_email = "admin@saferwall.com>"

[db]
server = "couchbase://couchbase"
username = "Administrator"
password = "password"

[nsq]
address = "nsqd01:4150"

[minio]
endpoint = "minio:9000"
seckey = "minio123"
accesskey = "minio"
spacename = "samples"
avatarspace = "images"
ssl = false

[auth]
signkey = "secret"

[smtp]
server = "smtp.example.com"
port = 465
user =  "user@example.com"
password = "password"
identity =  "identity"
sender =  "sender@example.com"