# Config used for local development.
# All dependent services (NSQ, Couchbase, ..) are assumed running in the
# same context.

# General app config.
address = ":8080" # The IP:Port. Defaults to 8080.
log_level = "debug" # Log level. Defaults to info.
jwt_signkey = "secret" # JWT sign key secret.
jwt_expiration = 72 # JWT expiration in hours. Defaults to 72 hours (3 days).
deployment_kind = "local" # Deployement kind, possible values: aws, gcp, azure, local.
max_file_size = 64 # Maximum file size to allow for samples in MB.
max_avatar_file_size = 1 # Maximum avatar size to allow for user profile picture in MB.

[ui]
address = "http://localhost:8000" # DSN for the frontend.

[db]
server = "couchbase://localhost" # DSN for connecting to the database
username = "Administrator" # Username used to access the db.
password = "password" # Password used to access the db.
bucket_name = "sfw" # Name of the couchbase bucket.

[nsq]
address = "localhost:4150" # The data source name (DSN) for connecting to the broker server (NSQD).
topic = "filescan" # Topic name to produce to.

[storage]
files_container_name = "samples" # Container name for samples.
avatars_container_name = "images" # Container name for avatars.
    [storage.local]
    root_dir = "~/saferwall/files"    # Full path to the directory where to store the files.

[smtp]
server = "smtp.example.com"
port = 465
user = "user@example.com"
password = "password"
identity = "identity"
sender = "sender@example.com"
