name: Build & Test

on: [push, pull_request]

jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build
        run: go build -v ./...

      - name: Test With Coverage
        run: go test ./... -race -coverprofile=coverage -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage

      - name: Run Vet & Lint
        run: |
          go vet .
          golint -set_exit_status=1 .
