name: Release
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
env:
  IMAGE: saferwall/webapis
jobs:
  build-container:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate build version
        id: prep
        run: |
          version=$(cat VERSION)
          echo "::set-output name=BUILD_VERSION::${version}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_VERSION }}